///MongoDb does not use schema, but according to the folder structure in Ensemble
///this is required to define the schema on sql

namespace Crud.Employee.Api.Models
{
    public class Employee
    {
        //Id is automatically generated by the database engine
        public string id { get; set; }
        public string Firstname {get;set;}
        public string Lastname { get; set; }
        public string Email { get; set; }

    }
}